/**
 * YAMNet's log-mel front end, reimplemented for the browser.
 *
 * This file is the one place where "close enough" is not good enough: the ONNX
 * model was exported from weights that expect exactly the features TensorFlow
 * produces, so every constant and rounding rule here mirrors
 * `embedders/yamnet/features.py` and `params.py` in the buzzdetect repo.
 * `test/melspec.test.ts` checks the output against patches generated by the
 * real TensorFlow pipeline.
 *
 * Deliberate correspondences worth not "cleaning up":
 *   - the window is a PERIODIC Hann (`tf.signal.stft`'s default);
 *   - the mel matrix zeroes its DC row, as `linear_to_mel_weight_matrix` does;
 *   - the log is taken of `mel + 0.001`, not of a clamped mel;
 *   - the tail padding follows `pad_waveform`, including its integer
 *     truncations and its float32 division.
 *
 * Memory: patches are produced on demand for a requested range rather than
 * materialised for the whole file. An hour of audio would otherwise need ~90 MB
 * of log-mel before inference even starts.
 */

import { RealFft, hannPeriodic } from './fft';

export const SAMPLE_RATE = 16000;
export const STFT_WINDOW_SECONDS = 0.025;
export const STFT_HOP_SECONDS = 0.010;
export const PATCH_WINDOW_SECONDS = 0.96;
export const MEL_BANDS = 64;
export const MEL_MIN_HZ = 125;
export const MEL_MAX_HZ = 7500;
export const LOG_OFFSET = 0.001;

export const WINDOW_SAMPLES = Math.round(SAMPLE_RATE * STFT_WINDOW_SECONDS); // 400
export const HOP_SAMPLES = Math.round(SAMPLE_RATE * STFT_HOP_SECONDS); // 160
export const FFT_SIZE = 2 ** Math.ceil(Math.log2(WINDOW_SAMPLES)); // 512
export const SPECTROGRAM_BINS = FFT_SIZE / 2 + 1; // 257
/** STFT frames in one patch: 0.96 s at a 10 ms hop. */
export const PATCH_FRAMES = Math.round(PATCH_WINDOW_SECONDS / STFT_HOP_SECONDS); // 96
export const PATCH_VALUES = PATCH_FRAMES * MEL_BANDS;

const MEL_BREAK_FREQUENCY_HZ = 700.0;
const MEL_HIGH_FREQUENCY_Q = 1127.0;

/** HTK mel scale, the one TensorFlow's mel matrix uses. */
export function hertzToMel(hz: number): number {
  return MEL_HIGH_FREQUENCY_Q * Math.log(1.0 + hz / MEL_BREAK_FREQUENCY_HZ);
}

export function melToHertz(mel: number): number {
  return MEL_BREAK_FREQUENCY_HZ * (Math.exp(mel / MEL_HIGH_FREQUENCY_Q) - 1);
}

/**
 * The mel filterbank, stored band by band as a contiguous run of weights.
 *
 * The dense matrix is 257x64 but each triangular band touches only a handful of
 * neighbouring FFT bins, so it is ~97% zeros. Skipping them turns the mel
 * projection from ~16k multiply-adds per frame into ~500 -- the difference
 * between the projection and the FFT dominating the front end.
 */
export interface MelBank {
  /** First spectrogram bin with a non-zero weight, per mel band. */
  starts: Int32Array;
  /** Number of contiguous bins, per mel band. */
  lengths: Int32Array;
  /** Offset into `weights` where each band's run begins. */
  offsets: Int32Array;
  weights: Float32Array;
}

/**
 * Builds the filterbank `tf.signal.linear_to_mel_weight_matrix` would return,
 * then compresses it to the banded form above.
 */
export function buildMelBank(): MelBank {
  const nyquist = SAMPLE_RATE / 2;
  const binMel = new Float64Array(SPECTROGRAM_BINS);
  for (let i = 0; i < SPECTROGRAM_BINS; i++) {
    binMel[i] = hertzToMel((i * nyquist) / (SPECTROGRAM_BINS - 1));
  }

  const loMel = hertzToMel(MEL_MIN_HZ);
  const hiMel = hertzToMel(MEL_MAX_HZ);
  const edges = new Float64Array(MEL_BANDS + 2);
  for (let i = 0; i < MEL_BANDS + 2; i++) {
    edges[i] = loMel + ((hiMel - loMel) * i) / (MEL_BANDS + 1);
  }

  const starts = new Int32Array(MEL_BANDS);
  const lengths = new Int32Array(MEL_BANDS);
  const offsets = new Int32Array(MEL_BANDS);
  const dense: number[][] = [];

  for (let j = 0; j < MEL_BANDS; j++) {
    const lower = edges[j];
    const center = edges[j + 1];
    const upper = edges[j + 2];
    const row: number[] = [];
    let start = -1;
    // Bin 0 is skipped: TF computes slopes from bin 1 up and pads a zero row
    // back on for DC, so the DC bin never contributes to any mel band.
    for (let i = 1; i < SPECTROGRAM_BINS; i++) {
      const lowerSlope = (binMel[i] - lower) / (center - lower);
      const upperSlope = (upper - binMel[i]) / (upper - center);
      const w = Math.max(0, Math.min(lowerSlope, upperSlope));
      if (w > 0) {
        if (start < 0) start = i;
        row.push(w);
      } else if (start >= 0) {
        break; // triangular bands are contiguous, so the first zero ends the run
      }
    }
    starts[j] = start < 0 ? 0 : start;
    lengths[j] = row.length;
    dense.push(row);
  }

  let total = 0;
  for (let j = 0; j < MEL_BANDS; j++) {
    offsets[j] = total;
    total += lengths[j];
  }
  const weights = new Float32Array(total);
  for (let j = 0; j < MEL_BANDS; j++) {
    weights.set(dense[j], offsets[j]);
  }

  return { starts, lengths, offsets, weights };
}

/**
 * Length YAMNet pads a waveform to, mirroring `features.pad_waveform`.
 *
 * The tail is padded so the clip yields a whole number of patches. The integer
 * truncations and the float32 division are reproduced rather than simplified,
 * because they decide whether a file ends on N or N+1 patches.
 */
export function paddedLength(numSamples: number, patchHopSeconds: number): number {
  const minWaveformSeconds = PATCH_WINDOW_SECONDS + STFT_WINDOW_SECONDS - STFT_HOP_SECONDS;
  const minNumSamples = Math.trunc(minWaveformSeconds * SAMPLE_RATE);
  const hopSamples = Math.trunc(patchHopSeconds * SAMPLE_RATE);

  let padding = Math.max(0, minNumSamples - numSamples);
  // The hop arithmetic below reasons about a clip already grown to the one-patch
  // minimum, but the padding it produces is still added to the ORIGINAL length --
  // `pad_waveform` pads the waveform it was given, and the samples it was short
  // by are already counted in `padding`.
  const clamped = Math.max(numSamples, minNumSamples);
  const afterFirstPatch = clamped - minNumSamples;
  // tf.cast(..., tf.float32) on both operands before the divide
  const hops = Math.ceil(Math.fround(Math.fround(afterFirstPatch) / Math.fround(hopSamples)));
  padding += hops * hopSamples - afterFirstPatch;

  return numSamples + padding;
}

/** Number of complete STFT frames in a padded waveform. */
export function frameCount(paddedSamples: number): number {
  if (paddedSamples < WINDOW_SAMPLES) return 0;
  return Math.floor((paddedSamples - WINDOW_SAMPLES) / HOP_SAMPLES) + 1;
}

/**
 * Computes log-mel patches on demand.
 *
 * One instance owns all of its scratch buffers and can be reused for the whole
 * session, including the live microphone path.
 */
export class MelPatchExtractor {
  readonly patchHopFrames: number;
  readonly patchHopSeconds: number;
  private readonly fft: RealFft;
  private readonly window: Float32Array;
  private readonly bank: MelBank;
  private readonly frameBuf: Float32Array;
  private readonly magBuf: Float32Array;

  /**
   * @param framehopProp buzzdetect's `framehop_prop`: 1 gives contiguous 0.96 s
   *   frames, 0.5 gives frames overlapping by half.
   */
  constructor(framehopProp = 1) {
    const hopFrames = PATCH_FRAMES * framehopProp;
    if (!Number.isInteger(hopFrames) || hopFrames < 1) {
      throw new Error(`framehop_prop ${framehopProp} does not give a whole number of frames`);
    }
    this.patchHopFrames = hopFrames;
    this.patchHopSeconds = PATCH_WINDOW_SECONDS * framehopProp;
    this.fft = new RealFft(FFT_SIZE);
    this.window = hannPeriodic(WINDOW_SAMPLES);
    this.bank = buildMelBank();
    this.frameBuf = new Float32Array(FFT_SIZE); // zero-padded tail stays zero
    this.magBuf = new Float32Array(SPECTROGRAM_BINS);
  }

  /** Total patches a waveform of `numSamples` yields. */
  patchCount(numSamples: number): number {
    const frames = frameCount(paddedLength(numSamples, this.patchHopSeconds));
    if (frames < PATCH_FRAMES) return 0;
    return Math.floor((frames - PATCH_FRAMES) / this.patchHopFrames) + 1;
  }

  /** Sample index where a given patch's first STFT frame begins. */
  patchStartSample(patchIndex: number): number {
    return patchIndex * this.patchHopFrames * HOP_SAMPLES;
  }

  /** Start time of a patch, in seconds -- the timestamp buzzdetect reports. */
  patchStartSeconds(patchIndex: number): number {
    return patchIndex * this.patchHopSeconds;
  }

  /**
   * Writes `count` patches starting at `firstPatch` into `out`, which must hold
   * `count * PATCH_VALUES` floats. Samples past the end of `wav` read as zero,
   * which is the padding YAMNet would have applied.
   */
  fillPatches(wav: Float32Array, firstPatch: number, count: number, out: Float32Array): void {
    const need = count * PATCH_VALUES;
    if (out.length < need) throw new Error(`out needs ${need} floats, got ${out.length}`);

    const { starts, lengths, offsets, weights } = this.bank;
    const { frameBuf, magBuf, window } = this;

    for (let p = 0; p < count; p++) {
      const frame0 = (firstPatch + p) * this.patchHopFrames;
      const patchOffset = p * PATCH_VALUES;

      for (let f = 0; f < PATCH_FRAMES; f++) {
        const sample0 = (frame0 + f) * HOP_SAMPLES;

        // Window into the FFT buffer, zero-filling anything past the waveform.
        const avail = Math.max(0, Math.min(WINDOW_SAMPLES, wav.length - sample0));
        for (let n = 0; n < avail; n++) frameBuf[n] = wav[sample0 + n] * window[n];
        for (let n = avail; n < WINDOW_SAMPLES; n++) frameBuf[n] = 0;

        this.fft.magnitudes(frameBuf, magBuf);

        const rowOffset = patchOffset + f * MEL_BANDS;
        for (let j = 0; j < MEL_BANDS; j++) {
          const start = starts[j];
          const len = lengths[j];
          const off = offsets[j];
          let acc = 0;
          for (let k = 0; k < len; k++) acc += magBuf[start + k] * weights[off + k];
          out[rowOffset + j] = Math.log(acc + LOG_OFFSET);
        }
      }
    }
  }
}
